### ISSUE TITLE
ypou

### ISSUE THREAD

**Issue by nestorbfgo** [beerose/everybody-gives-astro-supabase#1]
Cool, but if you follow the tutorial step by step there are errors :S

**Comment by beerose** [comment]
Can you tell me what kind of errors? Without specific informtion I can't provide help

**Comment by ckdev88** [comment]
i saw a very small one, not worth creating a new issue for :D
line 78 of src/components/NewGroupForm.tsx 
`setMembers(prev => prev.filter(m => m === memberName))`

`===` removes all but the one intended, should probably be `!== `

all in all nice tutorial though!

**Comment by beerose** [comment]
Ok, thanks a lot! Pushed a fix to this repo and to the blogpost
